Class {
	#name : #VHSMovie,
	#superclass : #Object,
	#instVars : [
		'title',
		'internationalTitles',
		'country',
		'language',
		'additionalLanguages',
		'producer',
		'filmingLocations',
		'plotSummary',
		'plotKeywords',
		'genres',
		'certificate',
		'releaseDate',
		'internationalReleaseDates',
		'budget',
		'worldwideIncomes',
		'countryIncomes',
		'runtime',
		'awards',
		'cast',
		'director'
	],
	#category : #'SlottyExample-plain'
}

{ #category : #accessing }
VHSMovie >> additionalLanguages [
	^ additionalLanguages
]

{ #category : #accessing }
VHSMovie >> additionalLanguages: anObject [
	additionalLanguages := anObject
]

{ #category : #accessing }
VHSMovie >> awards [
	^ awards
]

{ #category : #accessing }
VHSMovie >> awards: anObject [
	awards := anObject
]

{ #category : #accessing }
VHSMovie >> budget [
	^ budget
]

{ #category : #accessing }
VHSMovie >> budget: anObject [
	budget := anObject
]

{ #category : #accessing }
VHSMovie >> cast [
	^ cast
]

{ #category : #accessing }
VHSMovie >> cast: anObject [
	cast := anObject
]

{ #category : #accessing }
VHSMovie >> certificate [
	^ certificate
]

{ #category : #accessing }
VHSMovie >> certificate: anObject [
	certificate := anObject
]

{ #category : #accessing }
VHSMovie >> country [
	^ country
]

{ #category : #accessing }
VHSMovie >> country: anObject [
	country := anObject
]

{ #category : #accessing }
VHSMovie >> countryIncomes [
	^ countryIncomes
]

{ #category : #accessing }
VHSMovie >> countryIncomes: anObject [
	countryIncomes := anObject
]

{ #category : #accessing }
VHSMovie >> director [
	^ director
]

{ #category : #accessing }
VHSMovie >> director: anObject [
	director := anObject
]

{ #category : #accessing }
VHSMovie >> filmingLocations [
	^ filmingLocations
]

{ #category : #accessing }
VHSMovie >> filmingLocations: anObject [
	filmingLocations := anObject
]

{ #category : #accessing }
VHSMovie >> genres [
	^ genres
]

{ #category : #accessing }
VHSMovie >> genres: anObject [
	genres := anObject
]

{ #category : #accessing }
VHSMovie >> internationalReleaseDates [
	^ internationalReleaseDates
]

{ #category : #accessing }
VHSMovie >> internationalReleaseDates: anObject [
	internationalReleaseDates := anObject
]

{ #category : #accessing }
VHSMovie >> internationalTitles [
	^ internationalTitles
]

{ #category : #accessing }
VHSMovie >> internationalTitles: anObject [
	internationalTitles := anObject
]

{ #category : #accessing }
VHSMovie >> language [
	^ language
]

{ #category : #accessing }
VHSMovie >> language: anObject [
	language := anObject
]

{ #category : #accessing }
VHSMovie >> plotKeywords [
	^ plotKeywords
]

{ #category : #accessing }
VHSMovie >> plotKeywords: anObject [
	plotKeywords := anObject
]

{ #category : #accessing }
VHSMovie >> plotSummary [
	^ plotSummary
]

{ #category : #accessing }
VHSMovie >> plotSummary: anObject [
	plotSummary := anObject
]

{ #category : #accessing }
VHSMovie >> producer [
	^ producer
]

{ #category : #accessing }
VHSMovie >> producer: anObject [
	producer := anObject
]

{ #category : #accessing }
VHSMovie >> releaseDate [
	^ releaseDate
]

{ #category : #accessing }
VHSMovie >> releaseDate: anObject [
	releaseDate := anObject
]

{ #category : #accessing }
VHSMovie >> runtime [
	^ runtime
]

{ #category : #accessing }
VHSMovie >> runtime: anObject [
	runtime := anObject
]

{ #category : #accessing }
VHSMovie >> title [
	^ title
]

{ #category : #accessing }
VHSMovie >> title: anObject [
	title := anObject
]

{ #category : #accessing }
VHSMovie >> worldwideIncomes [
	^ worldwideIncomes
]

{ #category : #accessing }
VHSMovie >> worldwideIncomes: anObject [
	worldwideIncomes := anObject
]
