Class {
	#name : #VHSMovie,
	#superclass : #Object,
	#instVars : [
		'title',
		'internationalTitles',
		'country',
		'language',
		'additionalLanguages',
		'producer',
		'filmingLocations',
		'plotSummary',
		'plotKeywords',
		'genres',
		'certificate',
		'releaseDate',
		'internationalReleaseDates',
		'budget',
		'worldwideIncomes',
		'countryIncomes',
		'runtime',
		'awards',
		'cast',
		'director'
	],
	#category : #'SlottyExample-plain'
}
